### ISSUE TITLE
创建身分组后报错

### ISSUE THREAD

**Issue by starryeye-0001** [foxwhite25/qq.py#15]
### 摘要

创建身分组后报错

### 复现步骤

创建身分组

### 最小的复现代码

```python
await guild.create_role(name='test')
```

### 预期结果

创建身分组成功并且不报错

### 实际结果

创建身分组成功但是报错
File "c:\Users\13801\Documents\GitHub\Apocalypse-Barrier\qqbot.py", line 951
    await guild.create_role(name='test')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\13801\AppData\Local\Programs\Python\Python311\Lib\site-packages\qq\guild.py", line 959, in create_role
    role = Role(guild=self, data=data['role'], state=self._state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\13801\AppData\Local\Programs\Python\Python311\Lib\site-packages\qq\role.py", line 89, in __init__
    self.id: int = int(data['id'])
                       ~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable

### Intents

default + interaction

### 系统信息

最新的

### 核对清单

- [X] 我已经搜索了开放的问题，寻找重复的问题。
- [X] 如果有的话，我已经显示了整个 traceback。
- [X] 如果可见的话我已将我的 token 从代码中移除。

### 额外背景

_No response_

**Comment by foxwhite25** [comment]
抓个创建 role http 请求返回的 payload

**Comment by starryeye-0001** [comment]
DEBUG:qq.http:POST https://api.sgroup.qq.com/guilds/2344002540485864823/roles 与 {"color":0,"name":"test"} 已返回 200 Trace ID: b3b679ed08e7aa2eabd49603035d2b3c
DEBUG:qq.http:POST https://api.sgroup.qq.com/guilds/2344002540485864823/roles 已收到 {'role_id': '16543849', 'role': None}

**Comment by foxwhite25** [comment]
为什么他们role返回了none，这不是我能改的

**Comment by starryeye-0001** [comment]
已经让官方修复

**Comment by starryeye-0001** [comment]
还是有bug，qq修完后但是框架还报错
Traceback (most recent call last):
  File "c:\Users\13801\Documents\GitHub\Apocalypse-Barrier\qqbot.py", line 960, in get_event_id
    await guild.create_role(name='test')
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\13801\AppData\Local\Programs\Python\Python311\Lib\site-packages\qq\guild.py", line 959, in create_role
    role = Role(guild=self, data=data['role'], state=self._state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\13801\AppData\Local\Programs\Python\Python311\Lib\site-packages\qq\role.py", line 89, in __init__
    self.id: int = int(data['id'])
                       ~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable

Payload:

{
    "role_id": "16562434",
    "role": {
        "id": "16562434",
        "name": "test",
        "color": 4278190080,
        "hoist": 0,
        "number": 0,
        "member_limit": 3000
    }
}

**Comment by foxwhite25** [comment]
如果有问题请开新的issues，但最新版并没有这个问题 
![image](https://github.com/foxwhite25/qq.py/assets/39846845/4bf1fb7d-4816-4c9f-998c-c6cbd9993a52)
